# Header
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  Repository: repository
  Links: links
  About: about
rss: /atom.xml

# Enable/Disable menu icons.
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwesome icon. Key is case-senstive.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: fa-dashboard
  archives: fa-delicious
  categories: fa-folder
  tags: fa-tags
  repository: fa-code
  links: fa-gg
  about: fa-coffee
  sitemap: sitemap

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: ../images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: images/avatar.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Cofess
        author_title: Web Developer & Designer
        author_description: 喜欢新事物，关注前端动态，对新的技术有追求； 喜欢产品，喜欢设计，喜欢 coding。
        location: Shenzhen, China
        follow: https://github.com/cofess
    highlight: github # github, monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: /favicon.png # path to favicon
    social_links:
        github: https://github.com/cofess
        weibo: http://weibo.com/cofess
        twitter: https://twitter.com/iwebued
        # facebook: /
        # dribbble: /
        behance: https://www.behance.net/cofess
        rss: atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Content
excerpt_link: Read More
fancybox: true

# Site
site:
    title: Cofess - Web Developer & Designer # 页面title
    board: <p>欢迎交流与分享经验!</p> # 站点公告
    copyright: Cofess - Web Developer & Designer # 底部版权信息
    footLinks: false # options: true, false  # 网站底部是否显示友情链接

# Sidebar
sidebar: right
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# Github
github: 
  username: cofess
  popular_repos: [gulp-startkit,gulp-startpro]

# PV
pv:
    busuanzi:
        enable: true # options: true, false # 不蒜子统计
    leancloud:
        enable: false # options: true, false # leancloud统计
        app_id: 9XhaAqdAQpx9cRNSRLfgfO0U-gzGzoHsz # leancloud <AppID>
        app_key: yfPEhch9cH6CpTx9cplMeRTh # leancloud <AppKey>
        
# wordcount
postCount:
    enable: true
    wordcount: true # options: true, false # 文章字数统计
    min2read: true # options: true, false # 阅读时长预计         

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
